#include "webui/utils.h"

const char *htmlErrorTemplate =
"<!DOCTYPE html>"
"<html>"
"<head>"
	"<meta charset=\"utf-8\">"
	"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
	"<title>%i %s</title>"
	"<link href=\"/css/bootstrap.min.css\" rel=\"stylesheet\" />"
	"<link href=\"/css/technics.css\" rel=\"stylesheet\" />"
"</head>"
"<body>"
	"<div class=\"container bg-primary text-center\">"
		"<div class=\"row\">"
			"<div class=\"col-sm-100 p-5 bg-secondary text-center\">"
				"<h1>Technics SH-4060</h1>"
			"</div>"
		"</div>"
		"<div class=\"row\">"
			"<div class=\"col-sm-100\">"
				"<h2>%i %s</h2>"
				"<hr>"
				HTTP_STRING
			"</div>"
		"</div>"
	"</div>"
"</body>"
"</html>"
"<!-- We need some padding cause some browsers are stupid ant want to render their shit instead of this beautiful page we worked so much on... -->" HTTP_NEWLINE;
